remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: NBA players' salary analysis
description: 'Data source': Kaggle
'Data used: position, age, team name, points, assists, rebounds\nCalculated data: Player efficiency value'

show_downloads: ['true']