remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: NBA players salary analysis
description: Data source---Kaggle
             Data used---position, age, team name, points, assists, rebounds
             Calculated data---Player efficiency value
             function---forecasting salaries, helping GM or players to make decision and plan
show_downloads: ['true']